# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Neossh < Formula
  desc "An actively maintained fork and continuation of lazyssh"
  homepage "https://github.com/WhiteRoseLK/neossh"
  version "1.0.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/WhiteRoseLK/neossh/releases/download/v1.0.0/neossh_Darwin_x86_64.tar.gz"
      sha256 "097ae1043e563d55c425e69eaf1451359e248cca468826b88f05fbe64a96490f"

      def install
        bin.install "neossh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/WhiteRoseLK/neossh/releases/download/v1.0.0/neossh_Darwin_arm64.tar.gz"
      sha256 "d5df0d0a1768fa2fd9df6d7e017bfd12f9943616632d32d3e6efe6e3719a0ef7"

      def install
        bin.install "neossh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/WhiteRoseLK/neossh/releases/download/v1.0.0/neossh_Linux_x86_64.tar.gz"
      sha256 "933e711287a63cf37587b9bacec07ad6649ff345c6abe657c1960ded286c5e02"
      def install
        bin.install "neossh"
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/WhiteRoseLK/neossh/releases/download/v1.0.0/neossh_Linux_armv6.tar.gz"
      sha256 "671584f71c46b0875a6be591f3b8e02f8e6ab3233c90da960d65566a75307d08"
      def install
        bin.install "neossh"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/WhiteRoseLK/neossh/releases/download/v1.0.0/neossh_Linux_arm64.tar.gz"
      sha256 "d03455d52649ec0269f43e9eed23cf475680438d297eab7a14504a88c12270c9"
      def install
        bin.install "neossh"
      end
    end
  end

  conflicts_with "lazyssh", because: "neossh is an actively maintained fork of lazyssh"

  def caveats
    <<~EOS
      If you previously used lazyssh, neossh automatically migrates your
      metadata and settings from ~/.lazyssh to ~/.neossh. Your SSH config is unchanged.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/neossh --version")
  end
end
