# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Neossh < Formula
  desc "An actively maintained fork and continuation of lazyssh"
  homepage "https://github.com/WhiteRoseLK/neossh"
  version "2.0.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/WhiteRoseLK/neossh/releases/download/v2.0.0/neossh_Darwin_x86_64.tar.gz"
      sha256 "fd446f27f1681596d54a5cc300b00cc88346b15db9e17089265cf09e863df59d"

      def install
        bin.install "neossh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/WhiteRoseLK/neossh/releases/download/v2.0.0/neossh_Darwin_arm64.tar.gz"
      sha256 "d757584fae629b37e568c6ce6805159b6bfc2bb67915663ee5bc3dabd65fc0bc"

      def install
        bin.install "neossh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/WhiteRoseLK/neossh/releases/download/v2.0.0/neossh_Linux_x86_64.tar.gz"
      sha256 "bb7e18c6ccfdaec7e52595c542ecfa01174b1b5ee8fe52cdf35275c4774e7a00"
      def install
        bin.install "neossh"
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/WhiteRoseLK/neossh/releases/download/v2.0.0/neossh_Linux_armv6.tar.gz"
      sha256 "33f27264a722221249edd9ee7f27cf86a2ee9e865c9b39d7869201d8d819dfb5"
      def install
        bin.install "neossh"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/WhiteRoseLK/neossh/releases/download/v2.0.0/neossh_Linux_arm64.tar.gz"
      sha256 "8284007eb03583360b22f789cca541a3fdb4d38c598ed3eeee85f82cd12a3844"
      def install
        bin.install "neossh"
      end
    end
  end

  conflicts_with "lazyssh", because: "neossh is an actively maintained fork of lazyssh"

  def caveats
    <<~EOS
      If you previously used lazyssh, neossh automatically migrates your
      metadata and settings from ~/.lazyssh to ~/.neossh. Your SSH config is unchanged.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/neossh --version")
  end
end
