# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Neossh < Formula
  desc "An actively maintained fork and continuation of lazyssh"
  homepage "https://github.com/WhiteRoseLK/neossh"
  version "1.0.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/WhiteRoseLK/neossh/releases/download/v1.0.0/neossh_Darwin_x86_64.tar.gz"
      sha256 "52b2c7b20c81a2af85afe296cbf7d1fd81aa4538d1cddd9272f6dd97e893356f"

      def install
        bin.install "neossh"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/WhiteRoseLK/neossh/releases/download/v1.0.0/neossh_Darwin_arm64.tar.gz"
      sha256 "e39a66ae503f76e415c453f864a18110ace015a42fd52f0a8fdda09242dbf747"

      def install
        bin.install "neossh"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/WhiteRoseLK/neossh/releases/download/v1.0.0/neossh_Linux_x86_64.tar.gz"
      sha256 "506532c96fbad3741aa28fac4db59af1da9a03d48993a7eb776daec6407bbe86"
      def install
        bin.install "neossh"
      end
    end
    if Hardware::CPU.arm? and !Hardware::CPU.is_64_bit?
      url "https://github.com/WhiteRoseLK/neossh/releases/download/v1.0.0/neossh_Linux_armv6.tar.gz"
      sha256 "efb0f1c7571c756c6fc08445922c26a3cc5c16c73990d6a9db0c263bd7f1e7ca"
      def install
        bin.install "neossh"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/WhiteRoseLK/neossh/releases/download/v1.0.0/neossh_Linux_arm64.tar.gz"
      sha256 "723da89d33e8706f8023e99aa03bcf3afbee409b8f80584d937f6208caccbf3a"
      def install
        bin.install "neossh"
      end
    end
  end

  conflicts_with "lazyssh", because: "neossh is an actively maintained fork of lazyssh"
  conflicts_with "adembc/tap/lazyssh", because: "neossh is an actively maintained fork of lazyssh"

  def caveats
    <<~EOS
      If you previously used lazyssh, neossh automatically migrates your
      metadata and settings from ~/.lazyssh to ~/.neossh. Your SSH config is unchanged.
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/neossh --version")
  end
end
